/* Qualification OS home: current-state / record overview. Existing study data and review logic remain untouched. */
(function(){
  if(window.__qosCurrentHomeLoaded)return;
  window.__qosCurrentHomeLoaded=true;
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  const fmtMinutes=n=>{n=Math.max(0,Math.round(Number(n)||0));return `${Math.floor(n/60)}時間${n%60}分`};
  const fmtDate=s=>{if(!s)return '—';const d=new Date(s+'T00:00:00');return `${d.getFullYear()}/${d.getMonth()+1}/${d.getDate()}`};
  const daysUntil=s=>Math.ceil((new Date(s+'T00:00:00')-new Date(today()+'T00:00:00'))/86400000);
  const getData=()=>{try{return {q:eval('qualifications'),s:eval('subjects'),p:eval('problems'),st:eval('sessions')}}catch(e){return {q:[],s:[],p:[],st:[]}}};
  const getSB=()=>{try{return eval('sb')}catch(e){return null}};
  const getUser=()=>{try{return eval('currentUser')}catch(e){return null}};
  let reviewHistory=[];
  let originalOpenTab=null;
  let historyLoading=false;
  function storageKey(){const u=getUser();return `qualification-os-home-qualification-${u?.id||'guest'}`}
  function selectedQualificationId(q){const saved=localStorage.getItem(storageKey());if(saved&&q.some(x=>x.id===saved))return saved;const active=q.find(x=>x.result!=='passed')||q[0];if(active)localStorage.setItem(storageKey(),active.id);return active?.id||''}
  function ensureHome(){
    if(document.getElementById('qosCurrentHome'))return;
    const el=document.createElement('div');el.id='qosCurrentHome';
    el.innerHTML=`<div class="qch-shell"><header class="qch-header"><div><div class="qch-brand">資格勉強OS</div><div class="qch-subtitle">現在地・学習記録</div></div><div class="qch-header-actions"><button class="qch-icon" type="button" data-qch-nav="settings" aria-label="設定">⚙</button></div></header><main class="qch-main">
      <section class="qch-qualification card"><div class="qch-label">CURRENT QUALIFICATION</div><div class="qch-select-row"><select id="qchQualification" aria-label="現在の資格"></select></div><div class="qch-qualification-meta"><div><span>資格</span><strong id="qchQualificationName">—</strong></div><div><span>試験日</span><strong id="qchExamDate">—</strong></div></div></section>
      <section class="qch-study card"><div class="qch-section-title"><div><div class="qch-label">STUDY TIME</div><h2>学習時間</h2></div></div><div class="qch-time-grid"><div class="qch-time-item"><span>総学習時間</span><strong id="qchTotalTime">0時間0分</strong></div><div class="qch-time-item qch-time-focus"><span id="qchSelectedTimeLabel">選択中の資格</span><strong id="qchSelectedTime">0時間0分</strong></div></div></section>
      <section class="qch-review card"><div class="qch-section-title"><div><div class="qch-label">TODAY'S REVIEW</div><h2>今日の復習</h2></div><span class="qch-count" id="qchReviewCount">0問</span></div><div class="qch-review-grid"><div><span>復習対象</span><strong id="qchDue">0問</strong></div><div><span>期限超過</span><strong id="qchOverdue">0問</strong></div><div><span>本日分</span><strong id="qchTodayDue">0問</strong></div></div><button class="qch-primary" type="button" data-qch-nav="review">復習を始める</button></section>
      <section class="qch-attention card"><div class="qch-section-title"><div><div class="qch-label">ATTENTION</div><h2>要注意問題</h2><p>現在、連続して間違えている問題</p></div><span class="qch-count qch-count-warn" id="qchAttentionCount">0問</span></div><div id="qchAttentionList"></div><button id="qchAttentionMore" class="qch-secondary" type="button">すべて見る</button></section>
      </main><nav class="qch-bottom-nav" aria-label="メインナビゲーション"><button class="active" type="button" data-qch-nav="home">⌂<span>今日</span></button><button type="button" data-qch-nav="record">＋<span>記録</span></button><button type="button" data-qch-nav="status">▥<span>状況</span></button><button type="button" data-qch-nav="settings">⚙<span>設定</span></button></nav></div>`;
    document.getElementById('app')?.appendChild(el);
    el.querySelectorAll('[data-qch-nav]').forEach(b=>b.addEventListener('click',()=>qchNavigate(b.dataset.qchNav)));
    document.getElementById('qchQualification')?.addEventListener('change',e=>{localStorage.setItem(storageKey(),e.target.value);renderHome()});
    document.getElementById('qchAttentionMore')?.addEventListener('click',()=>toggleAttentionAll());
  }
  function hideOriginal(){const app=document.getElementById('app');if(!app)return;[...app.children].forEach(ch=>{if(ch.id!=='qosCurrentHome')ch.style.display='none'});const home=document.getElementById('qosCurrentHome');if(home)home.style.display='block';window.scrollTo({top:0,behavior:'smooth'})}
  function showOriginal(){const app=document.getElementById('app');if(!app)return;const home=document.getElementById('qosCurrentHome');if(home)home.style.display='none';[...app.children].forEach(ch=>{if(ch.id!=='qosCurrentHome')ch.style.display=''})}
  function qchNavigate(name){if(name==='home'){showHome();return}showOriginal();if(originalOpenTab)originalOpenTab(name==='record'?'record':name==='status'?'status':name==='settings'?'settings':'review')}
  function showHome(){hideOriginal();renderHome()}
  function getQualificationData(){const {q,s,p,st}=getData();const qid=selectedQualificationId(q);const qual=q.find(x=>x.id===qid)||null;return {q,s,p,st,qid,qual}}
  function dueForQualification(p,s,qid){const ids=new Set(s.filter(x=>x.qualification_id===qid).map(x=>x.id));const t=today();return p.filter(x=>ids.has(x.subject_id)&&x.status==='pending'&&x.next_review_date&&x.next_review_date<=t)}
  function historyForProblem(problemId){return reviewHistory.filter(x=>x.problem_id===problemId).sort((a,b)=>String(b.created_at||b.review_date||'').localeCompare(String(a.created_at||a.review_date||'')))}
  function consecutiveWrong(problemId){const rows=historyForProblem(problemId);let n=0;for(const row of rows){if(row.result==='wrong')n++;else if(row.result==='correct')break}return n}
  function attentionProblems(data){const subjectMap=new Map(data.s.map(x=>[x.id,x]));return data.p.map(p=>({p,n:consecutiveWrong(p.id),sub:subjectMap.get(p.subject_id)})).filter(x=>x.sub?.qualification_id===data.qid&&x.n>=2).sort((a,b)=>b.n-a.n||String(a.p.name).localeCompare(String(b.p.name),'ja'))}
  function renderQualificationSelect(q,selectedId){const select=document.getElementById('qchQualification');if(!select)return;select.innerHTML=q.length?q.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}${x.result==='passed'?'（試験済み）':''}</option>`).join(''):'<option value="">資格を設定してください</option>';select.value=selectedId}
  function renderAttention(items){const list=document.getElementById('qchAttentionList'),more=document.getElementById('qchAttentionMore');if(!list||!more)return;document.getElementById('qchAttentionCount').textContent=items.length+'問';if(!items.length){list.innerHTML='<div class="qch-empty">現在、要注意問題はありません。</div>';more.style.display='none';return}const expanded=list.dataset.expanded==='1';const shown=expanded?items:items.slice(0,4);list.innerHTML=shown.map(x=>`<div class="qch-attention-row"><div><strong>${esc(x.p.name)}</strong><span>${esc(x.sub?.name||'科目未設定')}</span></div><b>${x.n}回連続 ×</b></div>`).join('');more.style.display=items.length>4?'block':'none';more.textContent=expanded?'閉じる':'すべて見る'}
  function toggleAttentionAll(){const list=document.getElementById('qchAttentionList');if(!list)return;list.dataset.expanded=list.dataset.expanded==='1'?'0':'1';renderAttention(attentionProblems(getQualificationData()))}
  function renderHome(){ensureHome();const data=getQualificationData(),t=today();renderQualificationSelect(data.q,data.qid);const qual=data.qual;document.getElementById('qchQualificationName').textContent=qual?.name||'資格未設定';const examDate=qual?(qual.result==='failed'&&qual.next_exam_date?qual.next_exam_date:qual.exam_date):null;const d=examDate?daysUntil(examDate):null;document.getElementById('qchExamDate').textContent=examDate?`${fmtDate(examDate)}${d>=0?'（あと'+d+'日）':''}`:'未設定';const total=data.st.reduce((a,x)=>a+Number(x.minutes||0),0),selected=data.st.filter(x=>x.qualification_id===data.qid).reduce((a,x)=>a+Number(x.minutes||0),0);document.getElementById('qchTotalTime').textContent=fmtMinutes(total);document.getElementById('qchSelectedTimeLabel').textContent=(qual?.name||'選択中の資格')+'の学習時間';document.getElementById('qchSelectedTime').textContent=fmtMinutes(selected);const due=dueForQualification(data.p,data.s,data.qid),overdue=due.filter(x=>x.next_review_date<t).length,todayDue=due.filter(x=>x.next_review_date===t).length;document.getElementById('qchReviewCount').textContent=due.length+'問';document.getElementById('qchDue').textContent=due.length+'問';document.getElementById('qchOverdue').textContent=overdue+'問';document.getElementById('qchTodayDue').textContent=todayDue+'問';renderAttention(attentionProblems(data))}
  async function loadReviewHistory(){if(historyLoading)return;const sb=getSB(),u=getUser();if(!sb||!u)return;historyLoading=true;try{const {data,error}=await sb.from('problem_review_history').select('problem_id,review_date,result,created_at').eq('user_id',u.id).order('created_at',{ascending:false});if(error)throw error;reviewHistory=data||[];if(document.getElementById('qosCurrentHome')?.style.display!=='none')renderHome()}catch(e){console.warn('資格OSホーム: 復習履歴の取得に失敗しました',e)}finally{historyLoading=false}}
  function install(){ensureHome();originalOpenTab=window.openTab;if(!window.__qosOriginalOpenTab){window.__qosOriginalOpenTab=originalOpenTab;window.openTab=function(name){if(name==='home'){showHome();return}showOriginal();return window.__qosOriginalOpenTab?window.__qosOriginalOpenTab(name):undefined}}else originalOpenTab=window.__qosOriginalOpenTab;showHome();loadReviewHistory()}
  const wait=setInterval(()=>{if(document.getElementById('app')){clearInterval(wait);setTimeout(install,200)}},100);document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{if(document.getElementById('app'))install()},300));window.qosCurrentHomeRefresh=renderHome;
})();
